#!/bin/bash 
basepath=$(cd `dirname $0`; pwd)'/../'
pid=`cat $basepath'config/pid'`
stopService(){
	if [ $pid ];then
		if [ `ps -ef | grep $pid|wc -l` > 1 ]; then
			kill $pid
		fi
	else
		pkill node
	fi
	rm -rf $basepath'www/tmp/*'
	echo '' >  $basepath'config/pid'
}
startService(){
	cd $basepath
	nohup node $basepath'index.js'&
	if [ ! -d '/tmp/log/' ]; then 
		mkdir '/tmp/log/'
	fi
	if [ ! -d '/tmp/log/thrush/' ]; then 
		mkdir '/tmp/log/thrush/'
	fi
	if [ ! -d '/tmp/log/thrush/'`date +%Y` ]; then 
		mkdir '/tmp/log/thrush/'`date +%Y`
	fi
	if [ ! -d '/tmp/log/thrush/'`date +%Y/%m` ]; then 
		mkdir '/tmp/log/thrush/'`date +%Y/%m`
	fi
	if [ ! -d $basepath'www/tmp/' ]; then 
		mkdir $basepath'www/tmp/'
	fi
	echo '' >  '/tmp/log/thrush/'`date +%Y/%m/%d`
	echo '/tmp/log/thrush/'`date +%Y/%m/%d`
}
if [ $# -eq 0 ];then
	echo "you should pass args start|restart|stop"	
else
	case $1 in
		"stop") 
			stopService
			;;
		"start") 
			startService
			;;
		"restart") 
			stopService
			startService
			;;
	esac
fi
exit 0;
