#!/bin/bash 
basepath=$(cd `dirname $0`; pwd)'/../'
pid=`cat $basepath'config/pid'`
stopService(){
	if [ $pid ];then
	kill $pid
	fi
	rm -rf $basepath'www/tmp/*'
	echo '' >  $basepath'config/pid'
}
startService(){
	cd $basepath
	nohup node $basepath'index.js'&
	mkdir '/tmp/log/'
	mkdir '/tmp/log/thrush/'
	mkdir '/tmp/log/thrush/'`date +%Y`
	mkdir '/tmp/log/thrush/'`date +%Y/%m`
	mkdir $basepath'www/tmp/'
	echo '' >  '/tmp/log/thrush/'`date +%Y/%m/%d`
	echo '/tmp/log/thrush/'`date +%Y/%m/%d`
}
if [ $# -eq 0 ];then
	echo "you should pass args start|restart|stop"	
else
	case $1 in
		"stop") 
			stopService
			;;
		"start") 
			startService
			;;
		"restart") 
			stopService
			startService
			;;
	esac
fi
exit 0;
